<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Monio.Domain\Monio.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Categories\" />
    <Folder Include="Features\Wallets\" />
    <Folder Include="Features\Transactions\CreateExpense\" />
    <Folder Include="Common\" />
    <Folder Include="Features\Transactions\DeleteExpense\" />
    <Folder Include="Features\Transactions\GetTransaction\" />
    <Folder Include="Features\Transactions\GetTransactions\" />
    <Folder Include="Features\Transactions\UpdateExpense\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
