<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Monio.Domain\Monio.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Categories\" />
    <Folder Include="Features\Users\" />
    <Folder Include="Features\Wallets\" />
    <Folder Include="Features\Transactions\CreateExpense\" />
    <Folder Include="Common\" />
    <Folder Include="Features\Transactions\DeleteExpense\" />
    <Folder Include="Features\Transactions\GetTransaction\" />
    <Folder Include="Features\Transactions\GetTransactions\" />
    <Folder Include="Features\Transactions\UpdateExpense\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
